# Generated by Django 5.1.1 on 2024-09-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0002_adminprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='amount',
            new_name='balance',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='second_name',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
