# Generated by Django 5.1.1 on 2024-09-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0003_rename_amount_adminprofile_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='firstname',
            field=models.CharField(default='FirstName', max_length=150),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='secondname',
            field=models.CharField(default='LastName', max_length=150),
        ),
    ]
