# Generated by Django 5.1.1 on 2024-09-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0004_adminprofile_firstname_adminprofile_secondname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='secondname',
        ),
    ]
