# Generated by Django 5.1.1 on 2024-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0006_rename_balance_adminprofile_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='amount',
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
