# Generated by Django 5.1.1 on 2024-09-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0008_remove_transaction_user_fundtransfer_delete_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='account_number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='firstname',
            field=models.CharField(default='firstname', max_length=150),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='secondname',
            field=models.CharField(default='secondname', max_length=150),
        ),
    ]
