# Generated by Django 5.1.1 on 2024-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0009_adminprofile_account_number_adminprofile_firstname_and_more'),
    ]

    operations = [
    ]
