# Generated by Django 5.1.1 on 2024-09-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0010_populate_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminprofile',
            name='firstname',
            field=models.CharField(default='fisrtname', max_length=150),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='secondname',
            field=models.CharField(default='seconname', max_length=150),
        ),
    ]
