# Generated by Django 5.1.1 on 2024-09-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0011_alter_adminprofile_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='adminprofile',
            name='secondname',
        ),
    ]
