# Generated by Django 5.1.1 on 2024-09-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0012_account_remove_adminprofile_account_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
