# Generated by Django 5.1.1 on 2024-09-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_account', '0013_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
